services:
     twig.twig_extension.s3Url:
             class: Angle\Common\UtilityBundle\Twig\AmazonS3UrlExtension
             public: false
             arguments:
                 - { bucket_url: %cdn_prefix_url% }
             tags:
                 - { name: twig.extension }
